### ISSUE TITLE
can not train on SUNRGBD

### ISSUE THREAD

**Issue by 18306125266** [TUI-NICR/ESANet#30]
I change  the SE model,and I want to train the neural network on SUNRGBD.

I run the prepare_datasets.py .extract the images 、depths and labels.  

When i run the train.py ,there report :

Compute class weights
Traceback (most recent call last):
  File "train.py", line 552, in <module>
    train_main()
  File "train.py", line 87, in train_main
    c=args.c_for_logarithmic_weighting)
  File "/data/run01/scv2391/ESANet-main/src/datasets/dataset_base.py", line 169, in compute_class_weights
    label = self.load_label(i)
  File "/data/run01/scv2391/ESANet-main/src/datasets/sunrgbd/pytorch_dataset.py", line 134, in load_label
    label_dir[idx])).astype(np.uint8)
  File "/data/home/scv2391/.conda/envs/rgbd_segmentation/lib/python3.7/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'output_path-sun/SUNRGBD/kv2/kinect2data/000065_2014-05-16_20-14-38_260595134347_rgbf000121-resize\\label/label.npy'

But the label.npy exists .IS the '\\' due to the error ?  How can i correct it ？ thank you ！
![image](https://user-images.githubusercontent.com/67095486/137127359-ebe23657-8b5b-4cda-b065-bf6f67962da4.png)

**Comment by 18306125266** [comment]
&nbsp;Thank you。I corret the error.&nbsp;&nbsp;


New questions arose.I just changed the&nbsp;&nbsp;attention mechanism by PSA.&nbsp;

This is the PSA .
